export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_BUN = "ADD_BUN";
export const REMOVE_BUN = "REMOVE_BUN";
export const REBASE_ITEMS = "REBASE_ITEMS";
export const CALC_TOTAL_COST = "CALC_TOTAL_COST";
