export const WS_CONNECTION_START_OWN = "WS_CONNECTION_START_OWN";
export const WS_CONNECTION_SUCCESS_OWN = "WS_CONNECTION_SUCCESS_OWN";
export const WS_CONNECTION_ERROR_OWN = "WS_CONNECTION_ERROR_OWN";
export const WS_CONNECTION_USER_CLOSE_OWN = "WS_CONNECTION_USER_CLOSE_OWN";
export const WS_CONNECTION_CLOSED_OWN = "WS_CONNECTION_CLOSED_OWN";
export const WS_GET_MESSAGE_OWN = "WS_GET_MESSAGE_OWN";
export const WS_SEND_MESSAGE_OWN = "WS_SEND_MESSAGE_OWN";
